apiVersion: v1
kind: Service
metadata:
  name: remodel-app
  namespace: default
spec:
  selector:
    app: remodel-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer    # Change to ClusterIP + add Ingress for production
